---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgARO5/GSxhwV71drudlAaGAsMQ1UshNQVc2livyug6PvmbeJogz/M+xMgJwyn59qicQN1C8UyXJkAdTPZy7FGfpVGImraXkgE4VatZVAr5IwIgJwOEs4xADT+yYOh48PuDh13uRdo10NwvBxjchTsi0wKdcLktLcKQHrImsPqwmgnA3HoH7Ay2IEDqOCeTtVy9Hqa5Eh8CnHG52VjElphnRu1UHFYD1B/kV2vH+OZTHsqlJQYWn0GsG43QyVZ0sf1xp09UXfSnaulbEDjYi+ePqfgOw+8xQ3Ss/lMenfYPzSDxSkvEkQSRdCXEEMmv0iY267l/ORfWg4UxCDOPtfuqP/Ql1nmubus0ej7NFXDRWxNXHPJW9uwIp8mvhyXZv5aO/hMhz7wpslVZuZRBgGwWyy1J5WZ/xHBrmAuvH9GqKt1Zfl+ASKnx/PMjtsp+TeErlWoQcm4uwu3qpQ3M8ehhKHbEvT+gGrPGe+nR03P38Fi8yzcRRo8jVz8UXcNjVcx5naHoelNFcOaHh41OkI1thaIPaAYUeROlbuqfsEXn0DKSuA1oYOX7I/OWKa8VNuY2LkTAjIyRO/lajXVt028w6l6D2IN6fiQby12SN4xqEYGfl25zw9i/kOmAUtp9UPNRlbUYUCrn/c3R5aQTiMyblt0lx/VjGS6aOwDOyc2f4wr0g0WXM99Ny5ViEWtTXSmjrY7SUKFy+DQjJFQ==
    STRIPE_API_KEY: AgBrq5v7xVo4sNudtE4MPAR+A339hUubI16oVRmi4XDWICJOzDTQhE7f18NVPVctE/fCmYMmQozQ7FDQOMCRZK7omdDFlZ3Yalq8T+Cq20kAYuZzZSxe/fjGX3OuIqqIqSqVw7FFE1tC8I821FNEpX6MkapPigkQSpDHWiMDuKvMHUMweSGB0AjG5Cr9xDF/lqCqNE2s7ZVgkpaUWfJ+rCcUd99oiK07rxi9ObWoJgyJEkUv7dr1WGb7cAnWNti3PWnxekL+H0sx6RgrGqcd1IRKc+RoppVmXLPxtIjZuh1gXdhc0QOjEXcxV+YW6fc3eQ0LMIgdjYrjK9yK9lb6m5Tcj3TXSrRSRj2Jmd56ZJ5Z076ccvXAXVbW3+KUKIqISTX4kr7JvkrUxhWm9SdcWKzNi1wSvBQpjMKVFkMk3Ao1H4MI/5JaCdSNAXpf7IrWEVeGIq/gUvakK3UDG6O6v3DnjbT0uL2ryPVyuONBtoQnIEEPpwejXJDCjoAwtEctwaUCZAoa28ZXjHLGQRnENe+S+iy9GusAWYuBQfm+eLW+xsFT2Xc4gyEFVB3b37vRZ6kzlj1ozXc85hux9nVWMkf4ESkOraDht8bgxesklGDsMAO9sazcXPa8oUVq3Rntkp/S2kyZYNERpheEt7Va0jZBbVUjc/zml0arXNzHb4NR8HQf5YGYmgmoZKS+V3vowzci8Jhzl3wEthSa+xPAWiDOzLDnvQeWjtDA5vgiJw==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
